const glyphs={w:{k:'♔',q:'♕',r:'♖',b:'♗',n:'♘',p:'♙'},b:{k:'♚',q:'♛',r:'♜',b:'♝',n:'♞',p:'♟'}};
const $=id=>document.getElementById(id),files='abcdefgh';let board,turn,selected,bot='atlas',history,ended,thinking,castle,enPassant,lastMove;
const color=p=>p&&p===p.toUpperCase()?'w':'b',type=p=>p.toLowerCase(),name=(r,c)=>files[c]+(8-r),inside=(r,c)=>r>=0&&r<8&&c>=0&&c<8;
function fresh(){board=[['r','n','b','q','k','b','n','r'],Array(8).fill('p'),...Array.from({length:4},()=>Array(8).fill('')),Array(8).fill('P'),['R','N','B','Q','K','B','N','R']];turn='w';selected=null;history=[];ended=thinking=false;castle={w:{k:1,q:1},b:{k:1,q:1}};enPassant=null;lastMove=null;$('board').innerHTML='';$('gameOver').className='game-over';render();updateMoves();note('YOUR MOVE')}
function pseudo(a,b,attack=false){let[r,c]=a,[tr,tc]=b,p=board[r][c];if(!p||!inside(tr,tc))return false;let own=color(p),target=board[tr][tc];if(!attack&&target&&color(target)===own)return false;let dr=tr-r,dc=tc-c,ar=Math.abs(dr),ac=Math.abs(dc),t=type(p),clear=()=>{let sr=Math.sign(dr),sc=Math.sign(dc),x=r+sr,y=c+sc;while(x!==tr||y!==tc){if(board[x][y])return false;x+=sr;y+=sc}return true};if(t==='p'){let d=own==='w'?-1:1,start=own==='w'?6:1;if(attack)return ar===1&&ac===1;return dc===0&&!target&&(dr===d||(r===start&&dr===2*d&&!board[r+d][c]))||ac===1&&dr===d&&(target||enPassant===name(tr,tc))}if(t==='n')return ar*ac===2;if(t==='k')return ar<=1&&ac<=1;if(t==='b')return ar===ac&&clear();if(t==='r')return(dr===0||dc===0)&&clear();return(dr===0||dc===0||ar===ac)&&clear()}
function attacked(r,c,by){for(let i=0;i<8;i++)for(let j=0;j<8;j++)if(color(board[i][j])===by&&pseudo([i,j],[r,c],true))return true;return false}function inCheck(side){let king=side==='w'?'K':'k';for(let r=0;r<8;r++)for(let c=0;c<8;c++)if(board[r][c]===king)return attacked(r,c,side==='w'?'b':'w');return true}
function castleOK(side,k){let row=side==='w'?7:0,rook=k?7:0,way=k?[5,6]:[3,2],right=k?'k':'q';return castle[side][right]&&board[row][rook]===(side==='w'?'R':'r')&&way.every(c=>!board[row][c]&&!attacked(row,c,side==='w'?'b':'w'))&&!inCheck(side)}
function apply(a,b){let[r,c]=a,[tr,tc]=b,p=board[r][c],captured=board[tr][tc],side=color(p),cast=type(p)==='k'&&Math.abs(tc-c)===2,s={board:board.map(x=>[...x]),castle:JSON.parse(JSON.stringify(castle)),enPassant};board[tr][tc]=p;board[r][c]='';if(type(p)==='p'&&enPassant===name(tr,tc)&&!captured)board[r][tc]='';if(cast){let rf=tc>c?7:0,rt=tc>c?5:3;board[tr][rt]=board[tr][rf];board[tr][rf]=''}if(type(p)==='p'&&((side==='w'&&tr===0)||(side==='b'&&tr===7)))board[tr][tc]=side==='w'?'Q':'q';if(type(p)==='k')castle[side]={k:0,q:0};if(type(p)==='r'){if(c===0)castle[side].q=0;if(c===7)castle[side].k=0}if(captured&&type(captured)==='r'){let foe=side==='w'?'b':'w';if(tc===0)castle[foe].q=0;if(tc===7)castle[foe].k=0}enPassant=type(p)==='p'&&Math.abs(tr-r)===2?name((tr+r)/2,c):null;return s}function undo(s){board=s.board;castle=s.castle;enPassant=s.enPassant}
function legal(a,b){let p=board[a[0]][a[1]];if(!p||color(p)!==turn)return false;if(type(p)==='k'&&Math.abs(b[1]-a[1])===2)return b[0]===a[0]&&castleOK(turn,b[1]>a[1]);if(!pseudo(a,b))return false;let s=apply(a,b),bad=inCheck(turn);undo(s);return!bad}function candidates(side=turn){let old=turn;turn=side;let out=[];for(let r=0;r<8;r++)for(let c=0;c<8;c++)if(color(board[r][c])===side)for(let tr=0;tr<8;tr++)for(let tc=0;tc<8;tc++)if(legal([r,c],[tr,tc]))out.push([[r,c],[tr,tc]]);turn=old;return out}
function render(){let el=$('board');for(let r=0;r<8;r++)for(let c=0;c<8;c++){let p=board[r][c],cell=el.children[r*8+c];if(!cell){cell=document.createElement('button');cell.onclick=()=>click(r,c);el.append(cell)}cell.className='square '+((r+c)%2?'dark':'light');if(selected&&selected[0]===r&&selected[1]===c)cell.classList.add('selected');if(selected&&legal(selected,[r,c]))cell.classList.add(p?'capture':'target');if(cell.dataset.piece!==p){cell.dataset.piece=p;cell.replaceChildren();if(p){let piece=document.createElement('span');piece.className='piece '+color(p)+(lastMove&&lastMove[1][0]===r&&lastMove[1][1]===c?' moved':'');piece.textContent=glyphs[color(p)][type(p)];cell.append(piece)}}}}
function click(r,c){if(ended||thinking||turn!=='w')return;if(selected&&legal(selected,[r,c])){play(selected,[r,c]);selected=null;render();if(!ended)setTimeout(botMove,bot==='atlas'?180:260);return}selected=board[r][c]&&color(board[r][c])==='w'?[r,c]:null;render()}
function play(a,b){let p=board[a[0]][a[1]],taken=board[b[0]][b[1]],cast=type(p)==='k'&&Math.abs(a[1]-b[1])===2;lastMove=[a,b];apply(a,b);history.push(cast?(b[1]>a[1]?'O-O':'O-O-O'):`${name(...a)}${taken?'x':'-'}${name(...b)}`);turn=turn==='w'?'b':'w';updateMoves();let next=candidates();if(!next.length)finish(inCheck(turn)?(turn==='w'?'ATLAS CHECKMATES':'YOU CHECKMATE MILO'):'DRAW — STALEMATE');else if(inCheck(turn))note(turn==='w'?'CHECK — YOUR KING IS ATTACKED':'CHECK — BOT MUST RESPOND')}
function value(p){return({p:1,n:3,b:3,r:5,q:9,k:99})[type(p)]||0}function botMove(){if(ended)return;thinking=true;note(bot==='atlas'?'ATLAS IS THINKING…':'MILO IS TRYING HIS BEST…');setTimeout(()=>{let moves=candidates('b');if(!moves){finish(inCheck('b')?'YOU WIN':'DRAW — STALEMATE');return}let scored=moves.map(m=>{let score=(board[m[1][0]][m[1][1]]?value(board[m[1][0]][m[1][1]])*100:0)+Math.random()*8,s=apply(...m),check=inCheck('w');undo(s);return{m,score:score+(check?25:0)}});scored.sort((a,b)=>bot==='atlas'?b.score-a.score:a.score-b.score);play(...scored[0].m);thinking=false;render();if(!ended){note('YOUR MOVE');$('botThought').innerHTML=bot==='atlas'?'<span>ATLAS SAYS</span><p>"Check noted. I have a response for every line."</p>':'<span>MILO SAYS</span><p>"I saw that. I chose to ignore it."</p>'}},bot==='atlas'?220:300)}
function updateMoves(){let list=$('moves');list.innerHTML='';for(let i=0;i<history.length;i+=2){let li=document.createElement('li');li.innerHTML=`<span>${Math.floor(i/2)+1}.</span><em>${history[i]} ${history[i+1]||''}</em>`;list.append(li)}$('moveCount').textContent=String(Math.floor(history.length/2)+1).padStart(2,'0')}function note(t){$('statusText').textContent=t}function finish(title){ended=true;$('gameOver').innerHTML=`<div><h2>${title}</h2><p>${bot==='milo'?'Milo looks relieved.':'The board was always theirs.'}</p><button onclick="fresh()">PLAY AGAIN</button></div>`;$('gameOver').classList.add('show');note('EXPERIMENT COMPLETE')}
document.querySelectorAll('.bot-card').forEach(x=>x.onclick=()=>{bot=x.dataset.bot;document.querySelectorAll('.bot-card').forEach(y=>y.classList.toggle('selected',y===x));let a=bot==='atlas';$('opponentName').textContent=a?'ATLAS':'MILO';$('opponentTitle').textContent=a?'THE UNBEATABLE · RATING ∞':'THE GRACIOUS LOSER · RATING 001';$('opponentAvatar').textContent=a?'A':'M';$('opponentAvatar').className='mini-avatar '+(a?'atlas':'milo');fresh()});$('newGame').onclick=fresh;fresh();
